services:
  lanis-app:
    image: dewenni/lanis:latest
    network_mode: host
    container_name: lanis
    environment:
      - INTERVAL=3600     # Zeitintervall für Abfragen in Sekunden
      - HTTP_PORT=4040    # Umgebungsvariable für den HTTP-Server
    pull_policy: always
    volumes:
      - /volume1/docker/lanis/config:/app/config    # Verzeichnis für config.ini
      - /volume1/docker/lanis/output:/app/output    # Verzeichnis für output Dateien
      - /volume1/docker/lanis/log:/var/log          # Verzeichnis für log Datein